# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
driver = webdriver.Chrome()
driver.get("http://issue.zjetc.org/")
driver.set_window_size(1050, 840)
driver.find_element(By.NAME, "op_code").click()
driver.find_element(By.NAME, "op_code").send_keys("202025")
driver.find_element(By.NAME, "op_pwd").send_keys("123456")
driver.find_element(By.CSS_SELECTOR, ".el-button").click()
driver.find_element(By.CSS_SELECTOR, "#tab-3 > span").click()
driver.find_element(By.NAME, "code").click()
driver.find_element(By.NAME, "code").send_keys("浙B9KG01")
driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2) > .el-button").click()
element = driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1) > .el-button")
actions = ActionChains(driver)
actions.move_to_element(element).perform()
element = driver.find_element(By.CSS_SELECTOR, "body")
actions = ActionChains(driver)
actions.move_to_element(element, 0, 0).perform()
driver.find_element(By.CSS_SELECTOR, ".vehicle_item:nth-child(3)").click()
driver.find_element(By.CSS_SELECTOR, ".vehicle_info").click()